/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_Futronic_ScanApiHelper_Scanner */

#ifndef _Included_com_Futronic_ScanApiHelper_Scanner
#define _Included_com_Futronic_ScanApiHelper_Scanner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_Futronic_ScanApiHelper_Scanner
 * Method:    OpenDevice
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_Futronic_ScanApiHelper_Scanner_OpenDevice
  (JNIEnv *, jobject);

/*
 * Class:     com_Futronic_ScanApiHelper_Scanner
 * Method:    CloseDevice
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_Futronic_ScanApiHelper_Scanner_CloseDevice
  (JNIEnv *, jobject);

/*
 * Class:     com_Futronic_ScanApiHelper_Scanner
 * Method:    GetVersionInfo
 * Signature: ()Ljava/lang/String
 */
JNIEXPORT jstring JNICALL Java_com_Futronic_ScanApiHelper_Scanner_GetVersionInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_Futronic_ScanApiHelper_Scanner
 * Method:    GetImageSize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_Futronic_ScanApiHelper_Scanner_GetImageSize
  (JNIEnv *, jobject);

/*
 * Class:     com_Futronic_ScanApiHelper_Scanner
 * Method:    IsFingerPresent
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_Futronic_ScanApiHelper_Scanner_IsFingerPresent
  (JNIEnv *, jobject);

/*
 * Class:     com_Futronic_ScanApiHelper_Scanner
 * Method:    GetFrame
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_Futronic_ScanApiHelper_Scanner_GetFrame
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_Futronic_ScanApiHelper_Scanner
 * Method:    GetImage2
 * Signature: (I[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_Futronic_ScanApiHelper_Scanner_GetImage2
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     com_Futronic_ScanApiHelper_Scanner
 * Method:    SetOptions
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_Futronic_ScanApiHelper_Scanner_SetOptions
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_Futronic_ScanApiHelper_Scanner
 * Method:    GetLastErrorCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_Futronic_ScanApiHelper_Scanner_GetLastErrorCode
  (JNIEnv *, jobject);

/*
 * Class:     com_Futronic_ScanApiHelper_Scanner
 * Method:    Save7Bytes
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_Futronic_ScanApiHelper_Scanner_Save7Bytes
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_Futronic_ScanApiHelper_Scanner
 * Method:    Restore7Bytes
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_Futronic_ScanApiHelper_Scanner_Restore7Bytes
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_Futronic_ScanApiHelper_Scanner
 * Method:    SetNewAuthorizationCode
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_Futronic_ScanApiHelper_Scanner_SetNewAuthorizationCode
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_Futronic_ScanApiHelper_Scanner
 * Method:    SaveSecret7Bytes
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_Futronic_ScanApiHelper_Scanner_SaveSecret7Bytes
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_Futronic_ScanApiHelper_Scanner
 * Method:    RestoreSecret7Bytes
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_Futronic_ScanApiHelper_Scanner_RestoreSecret7Bytes
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     com_Futronic_ScanApiHelper_Scanner
 * Method:    SetDiodesStatus
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_Futronic_ScanApiHelper_Scanner_SetDiodesStatus
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_Futronic_ScanApiHelper_Scanner
 * Method:    GetDiodesStatus
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_Futronic_ScanApiHelper_Scanner_GetDiodesStatus
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
